// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnIF8wIGiz3oUthgw5jEFhcDTtBQLFkac',
    appId: '1:560632601585:web:5590941f58755e03440250',
    messagingSenderId: '560632601585',
    projectId: 'quickdesk-cd7d8',
    authDomain: 'quickdesk-cd7d8.firebaseapp.com',
    storageBucket: 'quickdesk-cd7d8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5pvGWfjl5XAH5m4_k3rmGlTjYSQdQpgg',
    appId: '1:560632601585:android:091efb1c9ed1ffd9440250',
    messagingSenderId: '560632601585',
    projectId: 'quickdesk-cd7d8',
    storageBucket: 'quickdesk-cd7d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdOb2nD0GiHeypbMocEqRZTQO5sVal6k0',
    appId: '1:560632601585:ios:0f8bbd4117053afa440250',
    messagingSenderId: '560632601585',
    projectId: 'quickdesk-cd7d8',
    storageBucket: 'quickdesk-cd7d8.firebasestorage.app',
    iosBundleId: 'com.example.quickdestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdOb2nD0GiHeypbMocEqRZTQO5sVal6k0',
    appId: '1:560632601585:ios:0f8bbd4117053afa440250',
    messagingSenderId: '560632601585',
    projectId: 'quickdesk-cd7d8',
    storageBucket: 'quickdesk-cd7d8.firebasestorage.app',
    iosBundleId: 'com.example.quickdestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnIF8wIGiz3oUthgw5jEFhcDTtBQLFkac',
    appId: '1:560632601585:web:62ec927c0c836164440250',
    messagingSenderId: '560632601585',
    projectId: 'quickdesk-cd7d8',
    authDomain: 'quickdesk-cd7d8.firebaseapp.com',
    storageBucket: 'quickdesk-cd7d8.firebasestorage.app',
  );
}
